[mypy]
python_version = 3.12
mypy_path = $MYPY_CONFIG_FILE_DIR/src
files = src, examples, tests
strict = True
warn_unreachable = True
pretty = True
show_error_code_links = True
exclude_gitignore = True
